### PR TITLE
allow update method to only update email address

### PR DESCRIPTION
**Pull request by phil-hudson**
usecase : user wants to change email only.

this change prevents a case where sending empty string to the server will cause the request to fail

## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by fenix-hub** [comment]
Isn't an empty string ignored? Do supabase accepts `""` as a new password value?

**Comment by phil-hudson** [comment]
True, to some extent it depends on the authentication password policies set in Supabase.It would probably be cleaner to add an additionally method for specifically updating the email address.If you agree I can make the changesSent from my iPhoneOn 24 Jan 2023, at 20:30, Nicolò Santilio ***@***.***> wrote:﻿
Isn't an empty string ignored? Do supabase accepts "" as a new password value?

**Comment by fenix-hub** [comment]
Agreed. Let's have different methods

**Comment by fenix-hub** [comment]
Thanks again! :)

**Pull request merged**
