### PR TITLE
Rework realtime client

### PR DESCRIPTION
**Pull request by stmn**
I reworked Realtime Client basing on that code:

https://github.com/godotengine/godot-demo-projects/blob/4.0-dev/networking/websocket_chat/websocket/WebSocketClient.gd

Reason: Currently Realtime Client is not usable at all (WebSocketPeer need to be handled differently than WebSocketClient from 3.x). After changes it looks somehow usable.

### CODE REVIEW

**Comment by fenix-hub** [comment]
Thanks, looks good to me for now.
Check the review and I'm ready with merging.

**Review by fenix-hub — CHANGES_REQUESTED** [review]
Could you add static typing?

**Comment by stmn** [comment]
> Could you add static typing?

Sure, added. I will test realtime feature more soon (probably) while making some game lobby mechanism or simple game.

**Review by fenix-hub — APPROVED** [review]

**Comment by fenix-hub** [comment]
Thanks!

**Pull request merged**
